spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rentcarv2
    hikari:
      username: postgres
      password: 6909
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    serialization:
      fail-on-empty-beans: false